name: Publish to npm

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable-cache
          yarn build

      - name: Publish to npm with next tag
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            npm publish --access public --tag next
          elif [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/master" ]; then
            # read the name of the package from package.json
            PACKAGE_NAME=$(node -p "require('./package.json').name")
            npm unpublish "$PACKAGE_NAME@next" --force
            npm publish --tag latest
          fi